import express from "express";
import cors from "cors";
import helmet from "helmet";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import pg from "pg";
const {Pool}=pg, app=express();
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:false});
const PORT=process.env.PORT||10000, SECRET=process.env.JWT_SECRET;
if(!process.env.DATABASE_URL||!SECRET) process.exit(1);
app.use(helmet()); app.use(cors({origin:true})); app.use(express.json({limit:"1mb"}));
app.get("/health",async(_q,s)=>{try{await pool.query("SELECT 1");s.json({ok:true})}catch{s.status(503).json({ok:false})}});
const token=u=>jwt.sign({id:u.id,name:u.name,role:u.role},SECRET,{expiresIn:"7d"});
function auth(req,res,next){const h=req.headers.authorization||"",t=h.startsWith("Bearer ")?h.slice(7):null;if(!t)return res.status(401).json({error:"Authentication required"});try{req.user=jwt.verify(t,SECRET);next()}catch{res.status(401).json({error:"Invalid or expired token"})}}
const roles=(...r)=>(q,s,n)=>r.includes(q.user.role)?n():s.status(403).json({error:"Not allowed"});

app.post("/api/auth/register",async(q,s)=>{try{const{name,phone,password,role="retailer"}=q.body;if(!name||!phone||!password)return s.status(400).json({error:"name, phone and password are required"});if(!["retailer","wholesaler","supplier"].includes(role))return s.status(400).json({error:"Invalid role"});if((await pool.query("SELECT id FROM users WHERE phone=$1",[phone])).rowCount)return s.status(409).json({error:"Phone already registered"});const hash=await bcrypt.hash(password,12),r=await pool.query("INSERT INTO users(name,phone,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id,name,phone,role",[name,phone,hash,role]),u=r.rows[0];s.status(201).json({user:u,token:token(u)})}catch(e){console.error(e);s.status(500).json({error:"Registration failed"})}});
app.post("/api/auth/login",async(q,s)=>{try{const{phone,password}=q.body,r=await pool.query("SELECT * FROM users WHERE phone=$1",[phone]);if(!r.rowCount||!(await bcrypt.compare(password||"",r.rows[0].password_hash)))return s.status(401).json({error:"Invalid phone or password"});const x=r.rows[0],u={id:x.id,name:x.name,phone:x.phone,role:x.role};s.json({user:u,token:token(u)})}catch{s.status(500).json({error:"Login failed"})}});

app.get("/api/products",auth,async(q,s)=>{const r=await pool.query("SELECT id,name,sku,unit,price,stock,owner_id,active FROM products WHERE active=true ORDER BY name");s.json(r.rows)});
app.post("/api/products",auth,roles("wholesaler","supplier"),async(q,s)=>{const{name,sku,unit="piece",price=0,stock=0}=q.body;if(!name)return s.status(400).json({error:"Product name is required"});const r=await pool.query("INSERT INTO products(name,sku,unit,price,stock,owner_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[name,sku||null,unit,Number(price),Number(stock),q.user.id]);s.status(201).json(r.rows[0])});
app.patch("/api/products/:id/stock",auth,roles("wholesaler","supplier"),async(q,s)=>{const n=Number(q.body.quantity);if(!Number.isFinite(n))return s.status(400).json({error:"Valid quantity required"});const r=await pool.query("UPDATE products SET stock=stock+$1,updated_at=NOW() WHERE id=$2 AND owner_id=$3 RETURNING *",[n,q.params.id,q.user.id]);if(!r.rowCount)return s.status(404).json({error:"Product not found"});await pool.query("INSERT INTO stock_movements(product_id,quantity,reason,user_id) VALUES($1,$2,'manual_adjustment',$3)",[q.params.id,n,q.user.id]);s.json(r.rows[0])});

app.post("/api/orders",auth,roles("retailer"),async(q,s)=>{const{wholesalerId,items=[]}=q.body;if(!wholesalerId||!items.length)return s.status(400).json({error:"wholesalerId and items are required"});const c=await pool.connect();try{await c.query("BEGIN");let total=0;for(const x of items){const p=await c.query("SELECT price,stock FROM products WHERE id=$1 AND owner_id=$2 AND active=true FOR UPDATE",[x.productId,wholesalerId]);if(!p.rowCount||Number(x.quantity)<=0||Number(x.quantity)>Number(p.rows[0].stock))throw Error("Product unavailable or insufficient stock");total+=Number(p.rows[0].price)*Number(x.quantity)}const o=await c.query("INSERT INTO orders(retailer_id,wholesaler_id,total,status) VALUES($1,$2,$3,'pending') RETURNING *",[q.user.id,wholesalerId,total]);for(const x of items){const p=await c.query("SELECT price FROM products WHERE id=$1",[x.productId]);await c.query("INSERT INTO order_items(order_id,product_id,quantity,unit_price) VALUES($1,$2,$3,$4)",[o.rows[0].id,x.productId,Number(x.quantity),p.rows[0].price])}await c.query("COMMIT");s.status(201).json(o.rows[0])}catch(e){await c.query("ROLLBACK");s.status(400).json({error:e.message})}finally{c.release()}});
app.get("/api/orders",auth,async(q,s)=>{const w=q.user.role==="retailer"?"retailer_id":q.user.role==="wholesaler"?"wholesaler_id":"supplier_id";s.json((await pool.query(`SELECT * FROM orders WHERE ${w}=$1 ORDER BY created_at DESC`,[q.user.id])).rows)});
app.post("/api/orders/:id/confirm",auth,roles("wholesaler"),async(q,s)=>{const c=await pool.connect();try{await c.query("BEGIN");const o=await c.query("SELECT * FROM orders WHERE id=$1 AND wholesaler_id=$2 FOR UPDATE",[q.params.id,q.user.id]);if(!o.rowCount||o.rows[0].status!=="pending")throw Error("Order not found or already processed");const its=await c.query("SELECT * FROM order_items WHERE order_id=$1",[q.params.id]);for(const x of its.rows){const u=await c.query("UPDATE products SET stock=stock-$1,updated_at=NOW() WHERE id=$2 AND owner_id=$3 AND stock>=$1 RETURNING id",[x.quantity,x.product_id,q.user.id]);if(!u.rowCount)throw Error("Insufficient stock");await c.query("INSERT INTO stock_movements(product_id,quantity,reason,user_id,order_id) VALUES($1,$2,'order_confirmed',$3,$4)",[x.product_id,-x.quantity,q.user.id,q.params.id])}const r=await c.query("UPDATE orders SET status='confirmed',updated_at=NOW() WHERE id=$1 RETURNING *",[q.params.id]);await c.query("COMMIT");s.json(r.rows[0])}catch(e){await c.query("ROLLBACK");s.status(400).json({error:e.message})}finally{c.release()}});
app.get("/api/ledger/:partyId",auth,async(q,s)=>s.json((await pool.query("SELECT id,entry_type,amount,note,created_at FROM ledger_entries WHERE party_id=$1 ORDER BY created_at DESC",[q.params.partyId])).rows));
app.post("/api/ledger",auth,roles("wholesaler"),async(q,s)=>{const{partyId,entryType,amount,note}=q.body;if(!partyId||!["credit","debit"].includes(entryType)||!Number.isFinite(Number(amount)))return s.status(400).json({error:"Invalid ledger entry"});const r=await pool.query("INSERT INTO ledger_entries(party_id,created_by,entry_type,amount,note) VALUES($1,$2,$3,$4,$5) RETURNING *",[partyId,q.user.id,entryType,Number(amount),note||null]);s.status(201).json(r.rows[0])});
app.use((_q,s)=>s.status(404).json({error:"Not found"})); app.listen(PORT,()=>console.log("RuralBiz API listening on "+PORT));
